name: Bug Report
description: Report a bug in roam-code
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below so we can
        reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what happened.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `roam init`
        2. Run `roam health`
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include any error messages or tracebacks.

  - type: input
    id: version
    attributes:
      label: roam-code version
      description: "Output of `roam --version`"
      placeholder: "e.g., roam-code 11.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      description: "Output of `python --version`"
      placeholder: "e.g., Python 3.12.0"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context about the problem (project size, languages indexed, etc.).
